# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.repository import Repository  # noqa: F401,E501
from swagger_server.models.user import User  # noqa: F401,E501
from swagger_server import util


class Pullrequest(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, title: str=None, repository: Repository=None, author: User=None):  # noqa: E501
        """Pullrequest - a model defined in Swagger

        :param id: The id of this Pullrequest.  # noqa: E501
        :type id: int
        :param title: The title of this Pullrequest.  # noqa: E501
        :type title: str
        :param repository: The repository of this Pullrequest.  # noqa: E501
        :type repository: Repository
        :param author: The author of this Pullrequest.  # noqa: E501
        :type author: User
        """
        self.swagger_types = {
            'id': int,
            'title': str,
            'repository': Repository,
            'author': User
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'repository': 'repository',
            'author': 'author'
        }
        self._id = id
        self._title = title
        self._repository = repository
        self._author = author

    @classmethod
    def from_dict(cls, dikt) -> 'Pullrequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The pullrequest of this Pullrequest.  # noqa: E501
        :rtype: Pullrequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pullrequest.


        :return: The id of this Pullrequest.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pullrequest.


        :param id: The id of this Pullrequest.
        :type id: int
        """

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this Pullrequest.


        :return: The title of this Pullrequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this Pullrequest.


        :param title: The title of this Pullrequest.
        :type title: str
        """

        self._title = title

    @property
    def repository(self) -> Repository:
        """Gets the repository of this Pullrequest.


        :return: The repository of this Pullrequest.
        :rtype: Repository
        """
        return self._repository

    @repository.setter
    def repository(self, repository: Repository):
        """Sets the repository of this Pullrequest.


        :param repository: The repository of this Pullrequest.
        :type repository: Repository
        """

        self._repository = repository

    @property
    def author(self) -> User:
        """Gets the author of this Pullrequest.


        :return: The author of this Pullrequest.
        :rtype: User
        """
        return self._author

    @author.setter
    def author(self, author: User):
        """Sets the author of this Pullrequest.


        :param author: The author of this Pullrequest.
        :type author: User
        """

        self._author = author